{% set version = "5.4.1" %}

package:
  name: pyyaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyYAML/PyYAML-{{ version }}.tar.gz
  sha256: 607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e
  patches:
    - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
    # Can be removed if https://github.com/yaml/pyyaml/pull/542 is merged
    - 0002-Close-resources.patch
    - 0003-Lowercase-cython.patch

build:
  number: 1
  script_env:
    - PYYAML_FORCE_LIBYAML=1
    - PYYAML_FORCE_CYTHON=1  # [python_impl == "cpython"]
  script:
    - python -m pip install .
    - python setup.py test

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - build
    - cython
    - pip
    - setuptools
    - wheel
    - yaml
  run:
    - python
    - yaml

test:
  imports:
    - yaml
    - _yaml   # [python_impl == "cpython"]
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyyaml.org/wiki/PyYAML
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: YAML parser and emitter for Python
  dev_url: https://github.com/yaml/pyyaml
  doc_url: http://pyyaml.org/wiki/PyYAML

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
