{% set version = "6.0.3" %}

package:
  name: pyyaml
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/P/PyYAML/pyyaml-{{ version }}.tar.gz
  sha256: d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f
  patches:
    - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
    - 0002-remove-setuptools-use-distutils-py38.patch  # [py<39]

build:
  number: 0
  skip: true  # [py<38]
  noarch: python  # [use_noarch]
  track_features:
    - pyyaml_no_compile    # [use_noarch]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python                        # [not use_noarch]
    - python {{ python_min }}.*     # [use_noarch]
    - cython
    - setuptools
    - packaging
    - pip
    - yaml
  run:
    - python                        # [not use_noarch]
    - python >={{ python_min }}.*   # [use_noarch]
    - yaml

test:
  imports:
    - yaml
    - _yaml   # [python_impl == "cpython" and not use_noarch]
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]
  requires:
    - pip
    - python {{ python_min }}.*     # [use_noarch]

about:
  home: http://pyyaml.org/wiki/PyYAML
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: YAML parser and emitter for Python
  dev_url: https://github.com/yaml/pyyaml
  doc_url: http://pyyaml.org/wiki/PyYAML

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
